const Products = [
  {
    _id: {
      $oid: "63c685934e04ba73e9106d28",
    },
    id: 1,
    name: "Faizan Shaikh",
    age: 23,
    Bloodgroup: "A-",
    subject: ["English", "Hindi", "Mathematics"],
    gender: "Male",
    __v: 0,
    ranking: 1,
  },
  {
    _id: {
      $oid: "63c6870d516ca8133e96019e",
    },
    id: 2,
    name: "Sameer Chaudry",
    age: 23,
    Bloodgroup: "B+",
    subject: ["Chemistry", "Physics", "Biology"],
    gender: "Male",
    __v: 0,
    ranking: 2,
  },
  {
    _id: {
      $oid: "63c687fabc3faaf98ab13fc7",
    },
    id: 3,
    name: "Ahmed",
    age: 25,
    Bloodgroup: "O",
    subject: ["Mathematics", "Physics", "Hindi"],
    gender: "Male",
    __v: 0,
    ranking: 3,
  },
  {
    _id: {
      $oid: "63c68a72ab934cd18a3357a4",
    },
    id: 4,
    name: "Jennefer",
    age: 36,
    Bloodgroup: "B+",
    subject: ["English", "Chemistry", "Mathematics"],
    gender: "Female",
    __v: 0,
    ranking: 4,
  },
  {
    _id: {
      $oid: "63c68adaab934cd18a3357a6",
    },
    id: 5,
    name: "Gwen",
    age: 42,
    Bloodgroup: "O+",
    subject: ["Biology", "Geometry", "Algebra"],
    gender: "Female",
    __v: 0,
    ranking: 5,
  },
  {
    _id: {
      $oid: "63c6927c71cb3b460b5f7b7a",
    },
    id: 6,
    name: "Rinky",
    age: 28,
    Bloodgroup: "A",
    subject: ["Geometry", "Hindi", "Biology"],
    gender: "Female",
    ranking: 6,
    __v: 0,
  },
  {
    _id: {
      $oid: "63c7ca13e583121d890adec3",
    },
    id: 7,
    name: "Arnold",
    age: 70,
    Bloodgroup: "A",
    subject: ["English", "Algebra", "Physics"],
    gender: "Male",
    ranking: 7,
    __v: 0,
  },
  {
    _id: {
      $oid: "63d0c2e984c9e80d0615c6b5",
    },
    id: 8,
    name: "Hafeez",
    age: 28,
    Bloodgroup: "B",
    subject: ["Chemistry", "Biology", "Mathematics"],
    gender: "Male",
    ranking: 8,
    __v: 0,
  },
  {
    _id: {
      $oid: "63d1128775bd5054d4dd8de1",
    },
    ids: 9,
    name: "Sova",
    age: 46,
    Bloodgroup: "O",
    subject: ["Physics", "Hindi", "English"],
    gender: "Male",
    ranking: 9,
    __v: 0,
  },
  {
    _id: {
      $oid: "63d9eda6ee4f84404850cda5",
    },
    id: 10,
    name: "Brim",
    age: 70,
    Bloodgroup: "A",
    subject: ["Mathematics", "Chemistry", "Biology"],
    gender: "Male",
    ranking: 10,
    __v: 0,
  },
];

export default Products;
